### ISSUE TITLE
Notifier: Remove the notifications which do not apply anymore after a Allow/Block action

### ISSUE THREAD

**Issue by harrwiss** [wokhansoft/WFN#100]
Notifier: After a user performs an Allow/Block action all notifications which do not apply anymore should be removed.

This includes also:
- cleanup code for rule matching and some refactoring
- improve the rules matching logic (rule naming must also be consistent)
- multiple service-names for service-name detection not needed anymore (simplify)
- limit the number of notifications for blocked connections in notifier

Mentioned in: #97

**Comment by harrwiss** [comment]
Hi @wokhan, I continue to work on this issue

**Comment by wokhan** [comment]
Hi @harrwiss, ok thanks!
I'm currently updating the UI (as it doesn't require to be fully focused on it, I can do it 10 minutes per day without actually forgetting something... as it's all "visible" ;-) ), I'll had screenshots in the corresponding issue (#86) so that you can all tell what you think of it instead of having to check the code by yourself.
