### ISSUE TITLE
Lots and lots of notifier.exe

### ISSUE THREAD

**Issue by vktec** [wokhansoft/WFN#24]
![many notifiers](https://user-images.githubusercontent.com/14016168/32606897-e05d8c1a-c54e-11e7-9010-63431ad767ff.PNG)

What are all those instances of `Notifier.exe` *doing*? They don't use much CPU each, but it really adds up (to 100% CPU usage!)

**Comment by TekieG** [comment]
I think that happens when notifier.exe is stuck trying to show the pop up. The program in question is what program is causing that.
This happens to me with any Adobe software because it’ll constantly attempt to connect to the outside and by constantly I mean like I can see the number of attempts go up just like a chronometer. At one point I had 3k notifier.exe and once I killed my adobe processes they all started to go away.

I had a batch file ready to kill notifier.exe and I ran it and then the pop up for adobe came up. I pressed allow and they all went away.

I don’t know a permanent fix for this. I just know how I got around it.

Sent from my iPhone

On Nov 9, 2017, at 8:11 AM, Samadi van Koten <notifications@github.com<mailto:notifications@github.com>> wrote:


[many notifiers]<https://user-images.githubusercontent.com/14016168/32606897-e05d8c1a-c54e-11e7-9010-63431ad767ff.PNG>

What are all those instances of Notifier.exe doing? They don't use much CPU each, but it really adds up (to 100% CPU usage!)

**Comment by vktec** [comment]
Okay, thanks for the hint. I'll see what I can figure out.

**Comment by AtlasHackert** [comment]
This is indeed a known limitation of the way WFN works. For every new connection attempt, a new Notifier.exe is launched. Some programs are badly behaved, and immediately and repeatedly retry making a connection, even when it's blocked by the firewall. This causes many Notifier.exe's to be launched.

(When you figure out what program is triggering this, please consider filing a bug report with them.)

**Comment by vktec** [comment]
Update: When closing all the programs I can and monitoring the security log, I see only a few programs connecting. Namely, `System` (which isn't really a program, I guess), `svchost.exe` and occasionally `werfault.exe`.

`System` and `svchost.exe` definitely have rules allowing them. I didn't notice any for `werfault.exe`, but it pops up a lot less frequently.

Even though there are allow rules in place, my current window still gets defocussed roughly every second or so due to an instance of `Notify.exe` opening. However, I see no notifications asking me to allow or deny the connection.

**Comment by AtlasHackert** [comment]
Then most likely Notifier.exe is crashing, causing a werfault.exe to start, and werfault.exe tries to connect to the internet, triggering a new Notifier.exe. What version of the .NET framework do you have installed, and in what folder did you place WFN?

**Comment by vktec** [comment]
Actually, I'm not sure if I have the .NET framework installed. I don't remember installing it manually. Though I probably need it for WFN to work at all. How do I find out the version? I can't see it in the programs list in Settings.

I put WFN in `C:\Program Files\Windows Firewall Notifier`.

**Comment by AtlasHackert** [comment]
That could be the problem. WFN currently needs to be able to write to its main folder (for the logfile), but many users can't. WFN can crash due to this, causing the exact behavior you are seeing. Can you "reinstall" WFN in a location where you have writing permission and try again?

**Comment by TekieG** [comment]
You can just move the file to “documents”(windows8.1 or newer) or “my documents” (Windows 7 or older) desktop works well took or if you have another drive you can put it there too.

Sent from my iPhone

On Nov 10, 2017, at 9:38 AM, DanielPharos <notifications@github.com<mailto:notifications@github.com>> wrote:


That could be the problem. WFN currently needs to be able to write to its main folder (for the logfile), but many users can't. WFN can crash due to this, causing the exact behavior you are seeing. Can you "reinstall" WFN in a location where you have writing permission and try again?

**Comment by vktec** [comment]
That seems to have been the issue. It also seems there wasn't a firewall rule allowing rundll through, so that started firing up a whole load of notifications. After temporarily enabling WFN a few times, I managed to allow it.
Now working perfectly. Thanks for the help!
