### ISSUE TITLE
Add a "I trust this program" option to disable all specific rule properties at once

### ISSUE THREAD

**Issue by rayman89** [wokhansoft/WFN#29]
When I set to prompt for outgoing connection I get multiple prompts per program, Could you make it so there is an option to allow all request forever from a certain program?

**Comment by AtlasHackert** [comment]
In the pop-up notifier, have you tried expanding the "Advanced", and modifying the rule to apply to the entire program (e.g. disable the options for "Target port" and "Protocol")?

**Comment by rayman89** [comment]
If I disable protocol It says there is no protocol assigned rule cannot be created or something like that. Either way if you have to do that to be able to allow a program is not intuitive at all for users. Having on the allow drop down menu something like "Trust this app" "Fully Allow" or something like that would be more intuitive faster and better for most users IMO.

**Comment by AtlasHackert** [comment]
True, this has been brought up before. Unfortunately, at the moment I don't have the time to implement that.

**Comment by rayman89** [comment]
I'll be looking forward for when it's implemented. Thank you.

**Comment by bsassone** [comment]
Perhaps an easier implementation would simply be to create two rules when the protocol is not selected: One for UDP and one for TCP.

**Comment by AtlasHackert** [comment]
That would leave out for example ICMP which the Windows Firewall can handle too.

**Comment by bsassone** [comment]
I suggested UDP and TCP because I consider these to be normal application traffic. If something is sending ICMP, IGMP or some other protocol, I want to know about it and not have it implicitly blocked.

Having said that, I don't feel this warrants any changes as there's no significant advantage in doing so and going down a path of trying to infer user intent is bad SW design, IMHO!

No, I'd much rather have the ability to modify/expand the address to block using CIDR. ;-)

**Comment by wokhan** [comment]
I like the "I fully trust this app" approach.That way users will be able to disable all specific settings at once.
Adding this in the to-dos for next release.
