### ISSUE TITLE
how to --> definitely <-- uninstall wfn please....

### ISSUE THREAD

**Issue by helppe** [wokhansoft/WFN#34]
hello,

yesterday i asked how to uninstall wfn since there is no installation/uninstallation process
see topic https://github.com/wokhansoft/WFN/issues/33

today when i set zonealarm to ask me for new connections it asked me if notifier.exe has to be allowed.... i answered no.
at this moment notifier.exe tryed to reach 127.0.0.1 (my own machine), why? wasn't it supposed to be inactive?

how to definitely "uninstall" wfn.

the fact that the folder with extracted files is always on my desktop is the reason of this activity?

**Comment by TekieG** [comment]
Inside of your wfn folder just run the batch file as administrator which will reset wfn, then delete the folder, that’s it.

Sent from my iPhone

On Feb 21, 2018, at 4:57 PM, helppe <notifications@github.com<mailto:notifications@github.com>> wrote:


hello,

yesterday i asked how to uninstall wfn since there is no installation/uninstallation process
see topic #33<https://github.com/wokhansoft/WFN/issues/33>

today when i set zonealarm to ask me for new connections it asked me if notifier.exe has to be allowed.... i answered no.
at this moment notifier.exe tryed to reach 127.0.0.1 (my own machine), why? wasn't it supposed to be inactive?

how to definitely "uninstall" wfn.

the fact that the folder with extracted files is always on my desktop is the reason of this activity?

**Comment by AtlasHackert** [comment]
Yes, running that batch file as admin should do the trick too.
