### ISSUE TITLE
How do you install WFN?

### ISSUE THREAD

**Issue by ylluminate** [wokhansoft/WFN#53]
What's the method to install WFN? It appears that if you simply drag the extracted folder to, say, C:\ and run it, no actual notifications arise when outbound connections occur.

Is there some missing documentation that reveals the secrets to this gem of an app?...

**Comment by wokhan** [comment]
Hi,
In fact I hate installers and this is why I didn't want one at first. All and every app should be made “portable”, so yes you basically only need to unzip the folder somewhere and run the Console executable. Once launched, head to the settings and you can then enable notifications here…
Removing the app works the other way: disable notifications then delete the folder. If it fails launching, the provided cmd file can also be used to disable notifications first.
Please note that the app still shows some known bugs, only one fellow developer currently works on the app and I haven't been on it for a while… No ETA for stable V2…
Hope this helps

________________________________
De : ylluminate <notifications@github.com>
Envoyé : Saturday, December 22, 2018 9:30:20 PM
À : wokhansoft/WFN
Cc : Subscribed
Objet : [wokhansoft/WFN] How do you install WFN? (#53)


What's the method to install WFN? It appears that if you simply drag the extracted folder to, say, C:\ and run it, no actual notifications arise when outbound connections occur.

Is there some missing documentation that reveals the secrets to this gem of an app?...

**Comment by ylluminate** [comment]
I don't disagree at all with your logic.  The problem I guess is: which is the console app? I assume it's `Notifier.exe`, right?  Do I need to set this up as a service?

The goal is to get this to start up each time with Windows.

This is very much what's been needed forever for Windows, it would seem, and is similar to `Little Snitch` on macOS... but when I fire up Windows workstations, the last thing I like to do is to not know what's going on with my networking and firewalls.

**Comment by wokhan** [comment]
Nope, it’s Console.exe, but anyway you don’t have to keep WFN running all the time (so you don’t need to add it to your start up sequence) :-)
Notifier.exe is indeed used to display the notifications, but it’s triggered by Windows itself through a special scheduled task (you can take a look at it through the “advanced task scheduler” once enabled).
The drawback is that since it’s not already running, there will be a slight delay before it shows up when a connection is blocked… and you can also face a “multiple notifier spawning issue” which shouldn't occur but is still here for some users anyway :-/

You are mentioning Windows workstations (plural), if you want to use WFN notifications in a professional environment, this last bug might be “dangerous” (as in “you might face unresponsive computers and have to reboot them, and disable WFN quickly afterwards”), especially if you also use Macs as Bonjour seems to trigger this issue.


De : ylluminate<mailto:notifications@github.com>
Envoyé le :samedi 22 décembre 2018 23:33
À : wokhansoft/WFN<mailto:WFN@noreply.github.com>
Cc : Jérôme Saliba<mailto:wokhan@outlook.com>; Comment<mailto:comment@noreply.github.com>
Objet :Re: [wokhansoft/WFN] How do you install WFN? (#53)


I don't disagree at all with your logic. The problem I guess is: which is the console app? I assume it's Notifier.exe, right? Do I need to set this up as a service?

The goal is to get this to start up each time with Windows.

This is very much what's been needed forever for Windows, it would seem, and is similar to Little Snitch on macOS... but when I fire up Windows workstations, the last thing I like to do is to not know what's going on with my networking and firewalls.

**Comment by ylluminate** [comment]
Well how interesting. The most recent release (https://github.com/wokhansoft/WFN/releases/download/v2.0-beta3/WFNV20BETA3.zip) does not have a `console.exe` packaged with it...

I guess since I have more Macs on my network (by 3x) than Windows machines, then I probably better lay low with this until the `Bonjour` issue is sorted out... :'(

**Comment by wokhan** [comment]
Oops, shame on me, I forgot it had been renamed to WFN.exe….
The other parts still apply ;-)
Regarding the issue, you can give it a try on one test machine though, maybe you won't face any problem…

________________________________
De : ylluminate <notifications@github.com>
Envoyé : Sunday, December 23, 2018 3:59:25 PM
À : wokhansoft/WFN
Cc : Jérôme Saliba; Comment
Objet : Re: [wokhansoft/WFN] How do you install WFN? (#53)


Well how interesting. The most recent release (https://github.com/wokhansoft/WFN/releases/download/v2.0-beta3/WFNV20BETA3.zip<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwokhansoft%2FWFN%2Freleases%2Fdownload%2Fv2.0-beta3%2FWFNV20BETA3.zip&data=02%7C01%7C%7C4dc1d44874b14c354fc608d668e73afa%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636811739669102562&sdata=Pas%2BspquND40O4WAkEy%2FMp5GPi%2F8C%2BwjVJQOBs18hYM%3D&reserved=0>) does not have a console.exe packaged with it...

I guess since I have more Macs on my network (by 3x) than Windows machines, then I probably better lay low with this until the Bonjour issue is sorted out... :'(

**Comment by yeon-mi** [comment]
@wokhan 👍 🥇  some of us like as common softwares. easy install (store on pc)/ update new version through setup quick etc. also newbies/non-technical computer users become complicate how to use.

then can you consider little bit for give us installer and also you can give portable one too as you prefer ^^

**Comment by DJCrashdummy** [comment]
let me suggest a compromise:
how about "packaging" for [Chocolatey](https://chocolatey.org/)? - so an installer isn't really needed, but it can be installed easily and updated automatically. :wink:

**Comment by ArchiveBase** [comment]
@DJCrashdummy another package manager :(

if possible make something like telegram portable might be better. see the different (or as a one app.exe then auto get extracted where we place it and click)
https://desktop.telegram.org
https://telegram.org/dl/desktop/win_portable (it can update too itself)

wait! @DJCrashdummy :D i only make @wokhan unhappy because he not prefer about it. just i said about a opinion about you @DJCrashdummy said thing

**Comment by 0xC4N1** [comment]
> let me suggest a compromise:
> how about "packaging" for Chocolatey?

Chocolatey is a solution for keeping software up to date. It is not a solution for simple initial setup processes because you're adding additional dependencies that need to be installed first.

I suppose creating an installer using a Visual Studio Setup Project is the best solution since this is a .NET application. https://www.youtube.com/watch?v=tGCuYwVzPFM

**Comment by leeuniverse** [comment]
Since this is a program that doesn't actually "install" anything, you guys can simply use an Archiver EXE creator (extractor) such as WinRAR has and I think a couple of other Archivers.

I seem to recall there are others out there too which function as an EXE extractor only, not actually part of an archive program.  Free ones too.  But I use WinRAR myself, which was the easiest method I found to easily pack files into an EXE.  They then run it and install the packed files to someone's drive, you can designate the default install location and they can change it on install if they want.

**Comment by wokhan** [comment]
Hi @leeuniverse, an auto extracting archive has already been considered, but I still wonder why a power-user portable tool should require an easier way to be "installed" than a manual extraction. Auto updating is a good clue, but it can be done (or could be...) through the console itself (at launch) without requiring additional service or alike, if everyone agrees it's enough to answer this issue.
I never use installers even for apps that come with one, so maybe my opinion is a bit biased 😁

**Comment by wokhan** [comment]
Adding the installer to the roadmap (which makes it a promise) ☺️
