### ISSUE TITLE
Build a Installer - Important (suggestion: Nullsoft)

### ISSUE THREAD

**Issue by ArchiveBase** [wokhansoft/WFN#55]
build a installer for this software then it'll easy for everyone to use as any other common.
suggestion: use https://nsis.sourceforge.io/Main_Page it's easy as nuts

edit: i didnt noticed https://github.com/wokhansoft/WFN/issues/53

**Comment by wokhan** [comment]
Hi,

Installers should be useless for “natively” portable apps, and WFN means to be portable (except for settings) :-)
And it is a tool for power users, as well, so I'm not sure those need an installer…
Anyway, since community’s interest is important (and your opinion is as much valuable as anyone else’s), maybe we can do a version with an installer if there is someone with time to work on it (which is the major issue with WFN: we don’t have that much time and the project evolves slowly :-/).

Thanks

________________________________
De : yeon-mi <notifications@github.com>
Envoyé : Friday, January 4, 2019 7:55:42 AM
À : wokhansoft/WFN
Cc : Subscribed
Objet : [wokhansoft/WFN] Build a Installer - Important (suggestion: Nullsoft) (#55)


build a installer for this software then it'll easy for everyone to use as any other common.
suggestion: use https://nsis.sourceforge.io/Main_Page<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnsis.sourceforge.io%2FMain_Page&data=02%7C01%7C%7C8475e7c7e9724f9bed2908d67211a54c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636821817439850392&sdata=BLNpln06KAYwrXW5ExmVF9xqub3DGr%2BAUSCotC0%2Bfkw%3D&reserved=0> it's easy as nuts

**Comment by yeon-mi** [comment]
https://github.com/wokhansoft/WFN/issues/53#issuecomment-451367327

**Comment by DJCrashdummy** [comment]
i guess this can be closed as duplicate of #53 and/or #21.

**Comment by ArchiveBase** [comment]
@DJCrashdummy yes i said it within first comment *edit but @wokhan didnt close it. so i close then.
