### ISSUE TITLE
Windows 10 Busy Mouse Cursor

### ISSUE THREAD

**Issue by TrevTheDev** [wokhansoft/WFN#61]
When I select Block and Prompt for outbound connections, I get a busy cursor flashing every second or so - and it corresponds with a background process Notifier.  If I allow outbound connects then the busy cursor stops flashing.

Thanks for a great solution - much better than anything else on the market.

I'm on windows 10.

**Comment by AtlasHackert** [comment]
A Notifier-process only pops up when a program is making an outbound connection. Figure out which program is misbehaving, fix that program, and you shouldn't see a Notifier-proces-a-second anymore.

**Comment by harrwiss** [comment]
I'm on windows 10 as well and am not getting this behaviour myself. Think @AtlasHackert is right that the WFN Notifier is not causing this mouse behaviour.

**Comment by wokhan** [comment]
Closed as it will be "solved" by either @harrwiss's event polling or the lightning-fast Notifier inter process communication I added.

**Comment by Marctraider** [comment]
Sorry if this is closed, but I have the same issue, but only on my laptop.

Checking 'security' log, the 'busy cursor' happens on each connection attempt which is explicitly blocked by WFN or my own custom rules.

**Comment by wokhan** [comment]
Hi @Marctraider, the issue was more about the notification (not the security log), but anyway with the next version you shouldn't be annoyed anymore as the global logic has been rewritten (no more polling for the security log, meaning lower CPU).
The said version is not ready yet, it's available as an alpha version in the release page (read: with known bugs and things not working as expected - so don't give it a try if not ready to deal with those :) ).
Thanks for your feedback

**Comment by Marctraider** [comment]
Thank you, I might try it! 

For the time being I found myself at ease with a simple context menu addition where I can selectively open specific (or all) ports on a certain executable while right clicking it! 

I'll defo check this out again at some point.
