### ISSUE TITLE
project stopped?

### ISSUE THREAD

**Issue by helppe** [wokhansoft/WFN#65]
hello,
the last beta version was released more than 1 year ago, does it mean the developpement has stoped?

**Comment by wokhan** [comment]
Hi! 
Well, development has been slowing down those last years (so much that it is indeed appearing stopped), mainly because I abandoned @AtlasHackert (who was almost alone on the project for years) since my free time is dedicated to other non open source projects...
That being said, WFN will never die, one day I'll probably decide to fix everything and add some new features, but right now it cannot be on my priorities list.

On a side note : what I don't get is that before it went open source, many people asked for it, and now that it has been offered to the community, nobody gets involved. I guess people only wanted to steal some code and leave right after (great, isn't it?).

Thank you for your interest in the project 🙂

Jérôme (aka Khan)

**Comment by AtlasHackert** [comment]
The main reason I stopped committing changes is because "it works for me". WFN is not perfect, true, but when balancing the amount-of-work-to-fix versus the amount-of-work-to-workaround, from a purely selfish perspective it doesn't make sense for me to invest. So the impetus would have to come from the community. Which brings me to the next bit.

> On a side note : what I don't get is that before it went open source, many people asked for it, and now that it has been offered to the community, nobody gets involved.
I 100% know what you are talking about. I've had it happen to pretty much of my projects as well. :(

**Comment by wokhan** [comment]
I guess we'll have to find a way to make the project more "attractive". Maybe a big update would help, but I tend to think as you do: as long as it works for me, I cannot invest time to investigate (sometimes with almost no clue about what happens for users facing issues).
To be continued... :)

**Comment by harrwiss** [comment]
Hi wokhan and AltlasHackert, 
think you did a fine job getting the project so far and it has promise! 

I was looking for a free FW just like that but when I tried it few weeks ago I immediately ran into issues e.g. UAC prompt and some unpredictable behaviour with the Notifier and error messages when allowing/blocking (on Win10Pro) hence I tried quite a few things. Not sure it would work properly for anybody downloading and trying it in the current state on Win10 - even tried it on a fresh/clean VM without success.

So I went downloading the source and thought maybe I could fix it for me although I'm much more into java programming. However it took me a while just to understand what the program tries to do. Think now I can understand a bit, but not yet enough to fix the security issues between Notifier and Rulemanager (impersonation and UAC prompt) properly since also debugging RuleManager is not straight forward.

I think what would be helpful to get others involved would be more background information on how to get started first e.g. what the purpose of the different parts is, how the Notifier gets triggered and communicates with the RuleManager i.e. is it really necessary to call the RuleManager via shell execute and why. Think mainly the security quirks need to get addressed first for a good out of the box user experience and also an installer would be nice.

Just my five cents ;)

Cheers, Harry

**Comment by AtlasHackert** [comment]
> Think now I can understand a bit, but not yet enough to fix the security issues between Notifier and Rulemanager (impersonation and UAC prompt) properly since also debugging RuleManager is not straight forward.
> Think mainly the security quirks need to get addressed first

Wait, what security issue are you talking about? The UAC prompt is PREVENTING a security issue!

**Comment by harrwiss** [comment]
Your're probably right - sorry for not making myself clear. The problem with the UAC prompt is more a usability issue for me e.g. every time when I want to add/block a connection from the notifier the UAC prompt appears - no fun having to click 2 times every time (and there are lots of connection requests the first time you start using WFN).
Additionally an error message dialog "the corresponding rule could not be created" comes up when trying to block temporarily for instance.
Also in the logfile there are many messages like this one, which indicate for me some issues with handling security/authentication:
2019/08/27 19:58:32 - SYSTEM [True] - [ERROR] Unable to initialize WFN
System.ComponentModel.Win32Exception: Unable to retrieve the current user token.
   at Wokhan.WindowsFirewallNotifier.Notifier.Program.EnsureUserSession(Int32 pid, String[] argv)
   at Wokhan.WindowsFirewallNotifier.Notifier.Program.Main(String[] argv)

**Comment by harrwiss** [comment]
I would like to apologize for my recent statement on 
`Not sure it would work properly for anybody downloading and trying it in the current state on Win10`

Recently my win10 installation got updated to 1903, causing my previously installed firewall to stop functioning. 
Therefore I gave WFN successfully another go and this time my experience was much better. Also the previously reported error in the logfile has disappeared so far.

All in all I think now WFN is quite usable to manage WAS rules when using WFN the right way i.e. there is no reason to create a rule for all the notifications - just for the ones you care about. After that WFN can be set to Block silently.

**Comment by harrwiss** [comment]
Think this issue can be closed now - it's progressing a bit ;)

Though I think we need a new Beta build to come out when time allows.

**Comment by kekukui** [comment]
@wokhan  

> **before it went open source, many people asked for it, and now that it has been offered to the community, nobody gets involved.** 

I think its just due to lack of publicity.  If you search for free firewalls, you just get a lot of bloated corporate crap, and WFN is hard to find.

> **I guess people only wanted to steal some code and leave right after (great, isn't it?)**

I have tested ~50 Windows firewalls and they all suck.  None of them look like they stole anything from WFN.  But I think you should steal some user interface design elements from Little Snitch, the best firewall ever. 😁

**_"Good artists copy; Great artists steal."_** - Steve Jobs
_____________________________
![688_1](https://user-images.githubusercontent.com/20834957/71206400-70a99700-2272-11ea-9ae2-7321e3f0e11f.jpg)

![little-snitch](https://user-images.githubusercontent.com/20834957/71206409-769f7800-2272-11ea-93fc-ff4167398716.png)

![littlesnitchsimplebbeditalert-100014741-orig 1](https://user-images.githubusercontent.com/20834957/71206415-7bfcc280-2272-11ea-9f60-26b748804494.png)
Little Snitch 3 The Best macOS Firewall
https://www.youtube.com/watch?v=M7Y5CtFK5Us

Little Snitch 3 overview
https://www.youtube.com/watch?v=o74QGbh_G3U

Firewall for Mac
https://www.youtube.com/watch?v=59rrkUFpB0k

**Comment by wokhan** [comment]
Closing the issue since the project is clearly not dead. Or undead. Whatever. 😁
