### ISSUE TITLE
Notifications fixed?

### ISSUE THREAD

**Issue by Gitoffthelawn** [wokhansoft/WFN#7]
Hello and welcome to GitHub!

I read this user-submitted reply on your old site, and am wondering if it has been fixed as of Beta 2:

> The 1.9 branches aren't being updated anymore. 2.0 is still in alpha stages, yes. So far, all versions seem to be suffering from a notification spam, that blows up task manager and causes 100% CPU usage. The developers are working hard to fix this issue, but none of them are getting paid, so it may take awhile for them to find a proper fix for it.

> Try each of them as they all give different results per user. The notification spam only happens with the "Block and Prompt" setting for outbound connections, but you can always try it with the other settings.

**Comment by AtlasHackert** [comment]
Some cases of it have been solved, yes, but if you have a misbehaving program opening thousands of connections, it will still bring down your system. This is a limitation in the way WFN and the Windows Firewall work, and is not something that (as far as I know) can be fixed.

So please give it a try, because luckily there are only very few of such misbehaving programs. :)

**Comment by Gitoffthelawn** [comment]
Thank you!
