### ISSUE TITLE
Migration to .Net Core 3.1

### ISSUE THREAD

**Issue by wokhan** [wokhansoft/WFN#74]
I'm creating this issue to track progress on WFN migration to .Net Core 3.1.
Shouldn't take long...

**Comment by wokhan** [comment]
**Status: all projects migrated, except for the Tests one (should do that tomorrow).**

Additional tests will be required to ensure the migration didn't break anything! @harrwiss  & @AtlasHackert, I'll probably need some help on that part if you have some time next week :-)

Branch netcore31 can already be checked out if someone wants to give it a try.

What's next: add a standalone publish profile (so that .net core won't be required on the user's computer) and play a bit with .Net Core 3 assemblies optimization to reduce the whole size. And if I can find some additional time: do some performance tests to compare with .Net Framework version...

**Comment by harrwiss** [comment]
Hi @wokhan, think thats a good idea but unfortunately it's a bit early for me, because your work is based on an old pull request from Oct 2019 which will probably make it quite hard for me to integrate especially when you do refactoring as well. 

Currently I work on a rewrite of Notifier and fixing issues in various places, which I hope to finish soon. Also I'm now using log4net for Logging etc.. Given the many changes/fixes since then I would very much appreciate if we could do the merging of my work first and then make the migration.

As I'm not aware yet what's involved in the migration, I have some questions:
- Do you  use a tool to make the migration or is it all manual? 
- Are there also API changes or is it backward compatible?
- Do you plan to do refactoring as well now?

Cheers.

**Comment by wokhan** [comment]
Hi @harrwiss,

Don't worry, migrating to .Net Core for WPF apps is really easy (as I in fact almost finished it already, looks like everything is working, so far).
So : it's a manual migration, mainly just updating the csproj files to use the Sdk format (instead of huge csproj files we are used to....).
It's backward compatible since it also relies on .Net Standard, but some minor changes or tweaks may be required.
You can check my commits and you'll see there is not that much changes. MS did a really good job with WPF support on .Net Core!

I'll do some refactoring, but I'll wait for your MR first (if you can push to a new branch and then ask for a MR, I'll check it ASAP and will handle any regression / compatibility issue for you, don't worry about that).

Thanks :-) (and welcome, as you're now an official WFN team member).

**Comment by AtlasHackert** [comment]
(I'm in the midst of switching computers, but I'll find some time to give it a go!)

**Comment by wokhan** [comment]
Thanks @AtlasHackert. 

Known "issue": I forgot (again) the console was to be named WFN.exe and not console.exe 😁 I'll fix today or tomorrow as it's just a conf thing.

And I still have to run both version (old/net core) to ensure everything looks and behave the same. Hopefully tonight... 

Have a nice day

**Comment by harrwiss** [comment]
Hi @wokhan/@AtlasHacker, thanks for having me here and let's see how we go along 😄 

I was quite busy on the weekend trying to complete the changes to make the Notification window a standalone module (without event log triggers) and with a new button design etc. - think it's nearing completion now but there are always more things to address. Let's see what you guys think and whether you'll agree to integrate it when you've seen it. 

> by joining the team you agree not to do any major change (as with log4net) without asking first 

Of course you decide what goes into master, thats fine for me. Log4Net was in fact not a major change i.e. just removed some Code in LogHelper and configured it - the LogHelper API is still the same with the big bonus that the logfiles don't grow forever.

When I get to it, I'll check out the dotnet31 code to get a feeling.

Cheers and have fun.

**Comment by wokhan** [comment]
Hi @harrwiss, indeed log4net isn't really a huge change, it was probably a bad example ;-)

Regarding the trigger-less notification window, I checked your code quickly, polling can work but I'm not sure it would be as reactive as a triggered event (especially with the modifications I made on sunday, which should improve reactivity), except of course if polling occurs every 100ms which might induce higher CPU usage (hypothetically).
But I think it's still really usefull, and that we should offer an option for that (trigger mode versus polling mode), if you didn't already implement one (didn't check).

Can't wait to check / merge all your updates :-)

Thanks!

Note: comments are not really related to the initial issue's subject (my fault), that's something I'll have to improve as well ;-)

**Comment by harrwiss** [comment]
Hi @wokhan, there where several reasons why I don't liked the notifier being triggered from the event log (by task scheduler):
* it's quite unpredictable when a trigger happens which then opens the notification window
* there is some overhead from parsing the command line for every event, security checks (via main)
* the mouse cursor showed a spinner when many connections opened in the background e.g. LCore tried to open something like 10 connections in the same milisec periodically or even freeze
* errors happening during notifier startup can cause it to crash on every blocked connection attempt - this got particularly nasty when windows error reporting is blocked ending up in a continous loop
* temp block rules didn't work at all
* switching to the console to turn off prompting was annoying
* debugging was not straight forward especially startup issues

With the new implementation I hope to improve these issues and being able to start notifier on demand or via task scheduler after login, balance load better, security handling, avoid locked install directory, etc. and there is now a small activity indicator besides the trayicon as well 😅 

Polling the event log in a background task was implemented, because simply adding an event handler to the SecurityLog doesn't work as I was expecting it to.  If there is a way in .net31 I'm happy to implement it 😃 

Implementation-vise I think it's nearly finished but needs of course some fine-tuning here and there besides testing.

If you have time, why not check it out and see how it works briefly (latest wip is in the feature/u7-notifier2-ui branch in my fork).

Cheers.

Note: And here are the consequences departing from the intend... 😃

**Comment by harrwiss** [comment]
Hi @wokhan, back to your original comment regarding testing of the netcore31 migration.

Just updated VS to get netcore31 and checked out the branch.

Generally the solution compiled and the console runs ok (except the test projects).

However there are some issues I noted immediately:

1. Notifier is not triggered at all - think these are the related errors:
`[ERROR] [AddItem() in P:\MyProjects\WindowsFirewallNotifier\WFN\Notifier\App.cs, line 226] Unable to add the connection to the pool.
System.IndexOutOfRangeException: Index was outside the bounds of the array.`
`\WindowsFirewallNotifier\WFN\Notifier\App.cs, line 226] Unable to add the connection to the pool.
System.NotSupportedException: Von diesem CollectionView-Typ werden keine Änderungen der "SourceCollection" unterstützt, wenn diese nicht von einem Dispatcher-Thread aus erfolgen.`

2. Security Log > Action column: Click on link 
`[ERROR] [Current_DispatcherUnhandledException() in P:\MyProjects\WindowsFirewallNotifier\WFN\Console\UI\Windows\MainWindow.xaml.cs, line 57] Unexpected error
System.UriFormatException: Invalid URI: The Uri string is too long.`

3. Security log > Button Eventlog Viewer
`The specified executable is not a valid application for this OS Platform`

All in all it seems promising to get netcore31 working relatively easy.

Cheers.

**Comment by wokhan** [comment]
Hi, 

I guess we'll do some optimizations if the Notifier has to be kept running (.net core will help here, but some refactoring would probably, also). 
Anyway I think we should keep both modes and let the user decide since many people told they liked WFN because it had no background process / agent... Maybe they changed their minds afterwards, but keeping two options for a while would be useful, still. Adding some telemetry and removing the trigger if it indeed doesn't serve anyone... 😊

Regarding the bugs, looks like I tested way too quickly (my baby girl doesn't let me that much time, if I may), I hopefully will be able to check and sort those out tomorrow morning before leaving.

Thanks for your help and tests!

**Comment by wokhan** [comment]
Hi all,
I started looking at aforementioned issues but then took 10 mins on (newly created) issue 75. No time left for this morning, will check back tonight.
Have a nice day

**Comment by harrwiss** [comment]
Hi @wokhan , I see you've been busy as well this morning 😉 

Pushed the merged result to branch *netcore/u7-netcore3-merged*:
- Notifier, Common, Console compile and run on my machine but needs more testing
- ContextMenu control was removed and replaced by ContextMenuStrip in netcore31
- Had to remove SingletonManager (and pipeserver) to make it work for me. The instance check is done in Notifier App.cs Main method at the moment
- Note that *tasktemplate.xml* was changed to start the Notification window after login once (the option for the user to set needs still to be added).
- For the moment I think it's better to stay with polling the windows event log because we have more control and notification is not time critical. What I really would like to avoid is, that the windows event log starts notifier instances when a block event occur's (e.g. causes mouse cursor flashing). 

Cheers.

**Comment by wokhan** [comment]
Hi @harrwiss, great, thank you!
Yeah it was time for some cleanup...
Regarding the singleton manager / pipe server, what issue did you face?

**Comment by harrwiss** [comment]
Hi @wokhan, thanks and very good we made that step to be in sync again 👍 

> Edit : using the pipe would allow having a light process in the background even with your polling solution, and defer UI to the Notifier when needed only. Best of both worlds.

Sorry, I had no time to go into the details of your new implementation with the pipe server to get the new Notifier running again. And... I figured you could re-introduce it easely if it still makes sense in the new Notifier version 😉. Does it work also without the *Notifier* being triggerd from the *windows event log* anymore? If yes, it's fine for me to use that approach.

**Comment by wokhan** [comment]
Yes it would work, but if we manage to lower the resources usage of Notifier when there's nothing to show, it would be unnecessary, after a second thought...

**Comment by harrwiss** [comment]
Ok, let's see ... maybe there are also uses in other places to improve things with that approach.

How should we go about addressing new problems/issues detected in the migrated version - create tickets for each?

**Comment by wokhan** [comment]
Yes, separate issues would be better (while linking to this one) 😊
Btw many parts of the app can be optimized by relying on the async/await tasks, relying on the dispatcher to render stuff (instead of keeping to much on the UI thread). I'll create an issue for that.
