### ISSUE TITLE
Security log is too slow and sometimes unusable

### ISSUE THREAD

**Issue by wokhan** [wokhansoft/WFN#75]
Hi all, 

The code in the event viewer is not optimized at all (at this point I cannot even load the page). In 5 years I learned a lot (not even mentionning .Net evolved as well!) so I've some quick means to improve that, will do that ASAP.

_@harrwiss if your fork includes fixes for this (TL;DR), please tell and I'll wait for the merge request to go on with optimizations (as I do with refactoring... it's hard for me to wait as I guess there is a lot I could rewrite ;-) ).
Hope you'll be able to launch the MR soon :-)
Thanks_

**Comment by harrwiss** [comment]
Hi wokhan, not sure what slow means but on my machine it takes from around <1s-2s max to show the full list (netcore31 version). However I've seen situations, that it can get slow when the windows security event log gets very busy, but then all sorts of bad things can happen - notably with the Notifier.

Since the version you have is roughly 4months old there are many things I've done in the meantime in various places.

Today I also noticed, that there are more serious problems with that version: the Notifier.dll becomes locked for instance and even removing the scheduled job and logout didnot solve it (had to restart). Then I got suddenly Null Reference Exceptions trying to start the console (these problems I've fixed for sure) - to get rid of them now I needed to delete all setting files (local, roaming).

Think we need to make a decision now, whether you want to make a full merge of my u7-notifier2-ui branch now and we continue together from there. The alternative of trying to debug and fix things which may have been solved already is only blocking us from progressing I think. The downside is, that I have not much time until the weekend to clean it up.

Let me know how we should continue.
 
Thanks.

**Comment by wokhan** [comment]
Decision's already taken, go for the merge 😊

What I'd like to do is:
- create a new branch from master
- rebase yours on top of it (not sure if cross-repos rebase are allowed though... I'm clearly no git-master 😁) 
- and then merge it with the netcore31 one. 
That way we'd keep all your commits unaltered. 

Free time was scarce today for me as well, hopefully I'll be able to check and merge everything before this weekend (can't tell for sure) or during the weekend if not.

**Comment by wokhan** [comment]
Oh and regarding the issue: in fact the security log page never ends loading on my computer (well, it probably will after some time but after 10s I already considered it as a total failure).

I'm putting it in standby till the merge.

**Comment by harrwiss** [comment]
Ok, but I will not be able to do the merging (with probably some merge conflicts) until Friday evening.

Currently I have a compile problem since I switched to the netcore31 stream and back in VS - maybe you can give me a tip:

![image](https://user-images.githubusercontent.com/33778373/75921803-10ce8f80-5e62-11ea-81eb-2f5124552840.png)

I've checked the project properties 
![image](https://user-images.githubusercontent.com/33778373/75922010-7a4e9e00-5e62-11ea-969d-c4e6882a5675.png)

There are also no changes in the branch, so it should be as it was before but maybe something outside the branch changed in VS, however the SDK for 4.5.2 is still referenced in VS.

Also not idea why I should re-run NuGet restore 🏴 

But now I quit for today.

Cheers.

**Comment by wokhan** [comment]
Hi, I got this as well when I switched to master and back... Thought it was only me.
What I assume: the VS project cache (somewhere in %appdata%) somehow mixed up both versions and should be cleaned.
Didn't try and I won't be able to this morning 🙁

**Comment by harrwiss** [comment]
Hi, found this here (solves the problem with the build not working) 😉 
> https://developercommunity.visualstudio.com/content/problem/317628/your-project-does-not-reference-netframeworkversio.html
> The culprit appears to be a **project.assets.json file in the .OBJ folder**. The workaround is to delete all the bin and .OBJ folders and rebuild. MS notes that since there is a workaround, this a low-priority problem. Note that cleaning the solution did not help. **I had to manually delete the folders**. I guess the json file isn't considered a part of the build, even though it lives there.

**Comment by wokhan** [comment]
Thanks! I was overthinking the solution I guess! 😁

**Comment by harrwiss** [comment]
Could have been anything - had no clue from the error it could be that 🙃

**Comment by harrwiss** [comment]
Hi @wokhan, I'm on it for a while now but the netcore3 merge gives mit problems afterwards. Common/Console is working but have problems with Notifier - currently because of Windows.Forms.ContextMenu doesn't exist anymore (it should according to docu 💩 )

Will probably continue tomorrow.

Cheers.

**Comment by wokhan** [comment]
Hi, don't worry about side effects due to the migration, I can take care of it all. 
If you manage to do the mentioned rebase, I'll figure out the next steps 😊

**Comment by wokhan** [comment]
Oops, closed the issue by mistake (buttons are small on a smartphone 😁)

**Comment by wokhan** [comment]
BTW you can have a look at the csproj for Notifier, versus the console. A property is required to import WinForms related stuff 😊

**Comment by wokhan** [comment]
Duplicate of #22

**Comment by wokhan** [comment]
Closing this as a dup (yeah I know I created it 😁). 
@harrwiss please continue the discussion about .net core in issue #74 😊
