### ISSUE TITLE
Migrate to NUnit from XUnit (again)

### ISSUE THREAD

**Issue by harrwiss** [wokhansoft/WFN#89]
After looking more into XUnit vs. NUnit my preference is NUnit now because:
- better documentation and more widely used
- more pratical approach than xunit
- easier

All in all I think it's better suited to our purpose.

**Comment by harrwiss** [comment]
Hi @wokhan, I already made the migration and some other cleanup (will create a pull request afterwards for review).

Also I tried to use categories which can be used for filters when running the tests in CI/CD - I suppose it should work but haven't tried yet  e.g.
*nunit3-console Wokhan.WindowsFirewallNotifier.Console.Tests.dll --where "cat == IntegrationTestCategory"*

See filters: [Test-Selection-Language](https://github.com/nunit/docs/wiki/Test-Selection-Language)

The categories are shown as Traits here:

<img src="https://user-images.githubusercontent.com/33778373/76683141-03ec3180-6602-11ea-9f66-83b8bb46858d.png" width="400px"/>

Any objections/comments from your side or from @AtlasHackert ?

**Comment by wokhan** [comment]
Hi @harrwiss,
No problem for me, as said xunit was a first choice since I saw it in MS products (and others). NUnit might be alright. I'll check this when I'm back from holidays.
Cheers

**Comment by wokhan** [comment]
Hi, changes were merged.
Don't forget the other Tests projects (they aren't part of the solution anymore, is it on purpose? if so the folders should be removed as well).
They are still blocking the automated tests (and so the nightlies builds), at least regarding Console.Tests since I didn't had the others. I'll remove them temporarily...
Thanks!

**Comment by harrwiss** [comment]
Hi, I wanted to first make the Common.Tests work with the chosen test framework and then migrate the others. Didn't expect, that they are blocking the builds when they are not part of the solution - hmm strange 🤔 

Will do that as part of #78 - closing this one.

BTW: With the "workflows\dotnetcore.yml" in the *.github" directory I experienced some problems when trying to push to my fork master - I'll create a ticket.

**Comment by wokhan** [comment]
I guess it's because of a bad habit. I launch dotnet build without specifying the solution, so that one is on me.
Anyway even the Common tests failed, I guess because it relies on external calls (actual firewall rules and so on), which will never work on CI/CD.
We'll see what we can do about that later ;-)

**Comment by harrwiss** [comment]
yes, but with the category filter cli option "cat == IntegrationTestCategory" it should exclude non integration tests.
